config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }, path_names: { sign_out: 'sign_out' }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }, path_names: { sign_out: 'sign_out' }

  root to: 'public/homes#top'

  get 'customers/information/edit', to: 'public/customers#edit', as: 'edit_customer_information'
  patch 'customers/information', to: 'public/customers#update'
  get 'customers/unsubscribe', to: 'public/customers#unsubscribe', as: :customers_unsubscribe
  patch 'customers/withdraw', to: 'public/customers#withdraw', as: :customers_withdraw
  get 'customers/my_page', to: 'public/customers#show', as: :customers_my_page

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :edit, :update, :show]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:show, :index, :new, :create, :edit, :update, :destroy]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]

    delete 'sign_out', to: 'sessions#destroy', as: :admin_sign_out
  end

  scope module: 'public' do
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all', as: :cart_items_destroy_all
    get 'orders/thanks', to: 'orders#thanks', as: :orders_thanks
    post 'orders/confirm', to: 'orders#confirm', as: :orders_confirm

    resources :genres, only: [:show]
    resources :customers, only: [:show, :edit, :update]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]

    get 'homes/top', to: 'homes#top', as: :homes_top
    get 'about', to: 'homes#about', as: :homes_about

    get 'registrations/new'
    get 'registrations/create'
  end

  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_scope :customer do
    resources :addresses
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def full_adresses
    "#{post_code} #{address} #{name}"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  has_one_attached :image

  def subtotal
    item.price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders

  validates :email, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def active_for_authentication?
    super && (is_active == true)
  end

end

app/models/end_user.rb
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |end_user|
      end_user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre

  scope :active, -> { where(is_active: true) }

  has_one_attached :image

  has_many :cart_items, dependent: :destroy

  has_many :order_detalis  #中間テーブル
  has_many :orders, through: :order_details


  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

 def get_item_image(width, height)
  image.variant(resize_to_limit: [width, height]).processed
 end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details # 中間テーブル
  has_many :items, through: :order_details # 注文には商品が多くある
  has_one_attached :image

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  enum status: {
     "入金待ち":0,
     "入金確認":1,
     "製作中":2,
     "発送準備中":3,
     "発送済み":4
  }

  enum making_sta: {
     "製作不可":0,
     "製作待ち":1,
     "製作中やで":2,
     "製作完了":3
  }

enum payment_method: ["クレジットカード", "銀行振込"]

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

enum making_status: { 製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all.page(params[:page]).per(8)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    #まだバリデーション設定してないので名前がからっぽでも編集できちゃいます！
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)#, notice: "会員情報を更新しました。"
    else
      render :edit
    end
  end


  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Devise after_sign_in_path_forオーバーライド
  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      admin_root_path # 管理者ログイン後のリダイレクト先
    else
      root_path # 顧客ログイン後のリダイレクト先
    end
  end
  
  before_action :set_genres

  private

  def set_genres
    @genres = Genre.all
  end
  
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/customers/edit.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-md-5 mb-3">
      <h3 class="px-4 text-center" style="background-color: #543520;"><%= @customer.first_name %> <%= @customer.last_name %>さんの会員詳細編集</h3>
    </div>
  </div>
  
  <%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch, local: true do |f| %>
    <% render "public/shared/error_messages", resource: @customer %>

     <div class="row">
      <label class="col-lg-3">名前</label>
      <div class="col-lg-3">
        <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name",  placeholder: "令和", class: "form-control" %>
      </div>
      <div class="col-lg-3">
        <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name",  placeholder: "道子", class: "form-control" %>
      </div>
    </div><br>

    <div class="row">
      <label class="col-lg-3">フリガナ</label>
      <div class="col-lg-3">
        <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "kana_first_name",  placeholder: "レイワ", class: "form-control" %>
      </div>
      <div class="col-lg-3">
        <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "kana_last_name",  placeholder: "ミチコ", class: "form-control" %>
      </div>
    </div><br>

    <div class="row">
      <label class="col-lg-3">郵便番号（ハイフンなし）</label>
      <div class="col-lg-3">
        <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code",  placeholder: "0000000", class: "form-control" %>
      </div>
    </div><br>

    <div class="row">
      <label class="col-lg-3">住所</label>
      <div class="col-lg-3">
        <%= f.text_field :address, autofocus: true, autocomplete: "address",  placeholder: "東京都渋谷区代々木神園町0-0", class: "form-control" %>
      </div>
    </div><br>

    <div class="row">
      <label class="col-lg-3">電話番号（ハイフンなし）</label>
      <div class="col-lg-3">
        <%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number",  placeholder: "0000000000", class: "form-control" %>
      </div>
    </div><br>

    <div class="row">
      <label class="col-lg-3">メールアドレス</label>
      <div class="col-lg-3">
        <%= f.text_field :email, autofocus: true, autocomplete: "email",  placeholder: "sample@example.com", class: "form-control" %>
      </div>
    </div><br>

    <div class="row">
      <label class="col-lg-3">会員ステータス</label>
      <div class="col-lg-3">
        <%= f.select :is_active, [['有効', true], ['退会済み', false]], {}, { class: 'form-control' } %>
      </div>
    </div><br>

    <div class="row">
      <div class="col-lg-12">
        <div class="row">
          <div class="col-lg-3"></div>
          <div class="col-lg-9"><%= f.submit "変更を保存", class: "btn btn-success" %></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container pt-5">
  <div class="row gy-5" style="display: flex; justify-content: space-between;">
    <div class="col-md-2">
      <h3 class="px-4" style="background-color: #543520;">会員一覧</h3>
    </div>
   </div>

  <div class="row">
    <div class="col">
      <table class="table mt-5">
        <thead class="thead">
        <tr style="background-color: #543520;">
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to customer.first_name, admin_customer_path(customer) %> <%= link_to customer.last_name, admin_customer_path(customer) %></td>
            <td><%= customer.email %></td>
            <td><span style="color:<%= customer.is_active ? 'green' : 'gray' %>;"><%= customer.is_active ? "有効":"退会" %></span></td>
          </tr>
        <% end %>
      </table>

    </div>  
  </div>    
  
  
  

     <div class="container d-flex justify-content-center">
      <%= paginate @customers, theme: 'bootstrap-5' %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-md-5 mb-3">
      <h3 class="px-4 text-center" style="background-color: #543520;"><%= @customer.first_name %> <%= @customer.last_name %>さんの会員詳細</h3>
    </div>
   </div>
    <div class="pl-5">
      <p class="my-3"><strong>会員ID </strong><span style="margin-left:150px;"><%= @customer.id %></span></p>
      <p class="my-3"><strong>氏名 </strong><span style="margin-left:160px;"><%= @customer.first_name %> <%= @customer.last_name %></span></p>
      <p class="my-3"><strong>フリガナ </strong><span style="margin-left:130px;"> <%= @customer.first_name_kana %> <%= @customer.last_name_kana %></span></p>
      <p class="my-3"><strong>郵便番号 </strong><span style="margin-left:130px;"><%= @customer.postal_code %></span></p>
      <p class="my-3"><strong>住所 </strong><span style="margin-left:160px;"><%= @customer.address %></span></p>
      <p class="my-3"><strong>電話番号 </strong><span style="margin-left:125px;"><%= @customer.phone_number %></span></p>
      <p class="my-3"><strong>メールアドレス </strong><span style="margin-left:80px;"><%= @customer.email %></span></p>
      <p class="my-3"><strong>会員ステータス </strong><span style="margin-left:90px; color:<%= @customer.is_active ? 'green' : 'gray' %>;"><%= @customer.is_active ? '有効' : '退会済み' %></span></p>

     <%= link_to '編集する', edit_admin_customer_path(@customer), class: 'btn btn-success btn-space' %>
     <!--%= link_to '注文履歴一覧へ', admin_customer_orders_path(@customer), class: 'btn btn-info' %-->

    </div>
  </div>
</div>