config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }, path_names: { sign_out: 'sign_out' }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }, path_names: { sign_out: 'sign_out' }

  root to: 'public/homes#top'

  get 'customers/information/edit', to: 'public/customers#edit', as: 'edit_customer_information'
  patch 'customers/information', to: 'public/customers#update'
  get 'customers/unsubscribe', to: 'public/customers#unsubscribe', as: :customers_unsubscribe
  patch 'customers/withdraw', to: 'public/customers#withdraw', as: :customers_withdraw
  get 'customers/my_page', to: 'public/customers#show', as: :customers_my_page

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :edit, :update, :show]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:show, :index, :new, :create, :edit, :update, :destroy]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]

    delete 'sign_out', to: 'sessions#destroy', as: :admin_sign_out
  end

  scope module: 'public' do
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all', as: :cart_items_destroy_all
    get 'orders/thanks', to: 'orders#thanks', as: :orders_thanks
    post 'orders/confirm', to: 'orders#confirm', as: :orders_confirm

    resources :genres, only: [:show]
    resources :customers, only: [:show, :edit, :update]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]

    get 'homes/top', to: 'homes#top', as: :homes_top
    get 'about', to: 'homes#about', as: :homes_about

    get 'registrations/new'
    get 'registrations/create'
  end

  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_scope :customer do
    resources :addresses
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def full_adresses
    "#{post_code} #{address} #{name}"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  has_one_attached :image

  def subtotal
    item.price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders

  validates :email, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def active_for_authentication?
    super && (is_active == true)
  end

end

app/models/end_user.rb
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |end_user|
      end_user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre

  scope :active, -> { where(is_active: true) }

  has_one_attached :image

  has_many :cart_items, dependent: :destroy

  has_many :order_detalis  #中間テーブル
  has_many :orders, through: :order_details


  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

 def get_item_image(width, height)
  image.variant(resize_to_limit: [width, height]).processed
 end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details # 中間テーブル
  has_many :items, through: :order_details # 注文には商品が多くある
  has_one_attached :image

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  enum status: {
     "入金待ち":0,
     "入金確認":1,
     "製作中":2,
     "発送準備中":3,
     "発送済み":4
  }

  enum making_sta: {
     "製作不可":0,
     "製作待ち":1,
     "製作中やで":2,
     "製作完了":3
  }

enum payment_method: ["クレジットカード", "銀行振込"]

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

enum making_status: { 製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
	# before_action :authenticate_admin!
  
	def show
		@order = Order.find(params[:id])
		@order_details = @order.order_details
	end

  def update 
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    if @order.update(order_params)
       @order_details.update_all(making_status: "製作待ち") if @order.status == "入金確認"
    end
      redirect_to admin_order_path(@order)
  end

  private
	def order_params
		params.require(:order).permit(:status)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Devise after_sign_in_path_forオーバーライド
  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      admin_root_path # 管理者ログイン後のリダイレクト先
    else
      root_path # 顧客ログイン後のリダイレクト先
    end
  end
  
  before_action :set_genres

  private

  def set_genres
    @genres = Genre.all
  end
  
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/orders/show.html.erb
<div class="container pt-5">
  <div class="row gy-5" style="display: flex; justify-content: space-between;">
    <div class="col-md-3 mb-3">
      <h3 class="px-4" style="background-color: #543520;">注文履歴詳細</h3>
    </div>
   </div>


      <div>
        <table>
          <tbody>
            <tr>
              <th>購入者</th>
              <td>
                <%= link_to admin_customer_path(@order.customer) do %>
                  <%= @order.customer.first_name %>
                  <%= @order.customer.last_name %>
                <% end %>
              </td>
            </tr>

            <tr>
              <th>注文日</th>
              <td><%= I18n.l @order.created_at %></td>
            </tr>

            <tr>
              <th>配送先</th>
              <td>〒<%= @order.postal_code %>
              <%= @order.address %>
              <%= @order.name %></td>
            </tr>

            <tr>
              <th>支払方法</th>
              <td><%= @order.payment_method %></td>
            </tr>

            <tr>
              <th>注文ステータス</th>
              <td>
                <%= form_for (@order), url: admin_order_path(@order) do |f| %>
                  <%= f.select :status, Order.statuses.keys.to_a %>
                  <%= f.submit "更新" %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="row">
        <div class="col-md-8">
          <table class="table mt-4">
            <thead class="thead">
              <tr>
                <th>商品名</th>
                <th>単価（税込）</th>
                <th>数量</th>
                <th>小計</th>
                <th>製作ステータス</th>
              </tr>
            </thead>
            <tbody>
              <% @order_details.each do |order_detail| %>
                <tr>
                  <td><%= order_detail.item.name %></td>
                  <td><%= (order_detail.price).floor.to_s(:delimited, delimiter: ',') %></td>
                  <td><%= order_detail.amount %></td>
                  <td><%= (order_detail.price * order_detail.amount).floor.to_s(:delimited, delimiter: ',') %></td>
                  <td>
                    <%= form_for (order_detail), url: admin_order_detail_path(order_detail) do |f| %>
                      <%= f.select :making_status, OrderDetail.making_statuses.keys.to_a %>
                      <%= f.submit '更新' %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <div class="col-mg-4 table-container align-self-end">
            <table>
              <tbody>
                <tr>
                  <td>商品合計</td>
                  <td><%= (@order.total_payment - @order.shipping_cost).to_s(:delimited, delimiter: ',') %> 円</td>
                </tr>

                <tr>
                  <td>送料</td>
                  <td><%= @order.shipping_cost.to_s(:delimited, delimiter: ',') %> 円</td>
                </tr>

                <tr>
                  <td>請求合計金額</td>
                  <td><%= @order.total_payment.to_s(:delimited, delimiter: ',') %> 円</td>
                </tr>
              </tbody>
            </table>
        </div>
      </div>
    </div>
  </div>
</div>