config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }, path_names: { sign_out: 'sign_out' }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }, path_names: { sign_out: 'sign_out' }

  root to: 'public/homes#top'

  get 'customers/information/edit', to: 'public/customers#edit', as: 'edit_customer_information'
  patch 'customers/information', to: 'public/customers#update'
  get 'customers/unsubscribe', to: 'public/customers#unsubscribe', as: :customers_unsubscribe
  patch 'customers/withdraw', to: 'public/customers#withdraw', as: :customers_withdraw
  get 'customers/my_page', to: 'public/customers#show', as: :customers_my_page

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :edit, :update, :show]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:show, :index, :new, :create, :edit, :update, :destroy]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]

    delete 'sign_out', to: 'sessions#destroy', as: :admin_sign_out
  end

  scope module: 'public' do
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all', as: :cart_items_destroy_all
    get 'orders/thanks', to: 'orders#thanks', as: :orders_thanks
    post 'orders/confirm', to: 'orders#confirm', as: :orders_confirm

    resources :genres, only: [:show]
    resources :customers, only: [:show, :edit, :update]
    resources :cart_items, only: [:index, :update, :destroy, :create]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]

    get 'homes/top', to: 'homes#top', as: :homes_top
    get 'about', to: 'homes#about', as: :homes_about

    get 'registrations/new'
    get 'registrations/create'
  end

  devise_scope :end_user do
    post 'end_users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_scope :customer do
    resources :addresses
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def full_adresses
    "#{post_code} #{address} #{name}"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  has_one_attached :image

  def subtotal
    item.price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders

  validates :email, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def active_for_authentication?
    super && (is_active == true)
  end

end

app/models/end_user.rb
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |end_user|
      end_user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre

  scope :active, -> { where(is_active: true) }

  has_one_attached :image

  has_many :cart_items, dependent: :destroy

  has_many :order_detalis  #中間テーブル
  has_many :orders, through: :order_details


  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

 def get_item_image(width, height)
  image.variant(resize_to_limit: [width, height]).processed
 end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details # 中間テーブル
  has_many :items, through: :order_details # 注文には商品が多くある
  has_one_attached :image

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  enum status: {
     "入金待ち":0,
     "入金確認":1,
     "製作中":2,
     "発送準備中":3,
     "発送済み":4
  }

  enum making_sta: {
     "製作不可":0,
     "製作待ち":1,
     "製作中やで":2,
     "製作完了":3
  }

enum payment_method: ["クレジットカード", "銀行振込"]

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

enum making_status: { 製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Devise after_sign_in_path_forオーバーライド
  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      admin_root_path # 管理者ログイン後のリダイレクト先
    else
      root_path # 顧客ログイン後のリダイレクト先
    end
  end
  
  before_action :set_genres

  private

  def set_genres
    @genres = Genre.all
  end
  
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", admin_root_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCAKE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      /* mainタグに背景画像を適用 */
      main {
        position: relative; /* オーバーレイを使用するために必要 */
        background-image: url('<%= asset_path('about_image3.jpg') %>');
        background-size: cover;
        background-position: center;
        min-height: 100vh; /* 画面全体の高さを確保 */
      }

      /* 透過オーバーレイ */
      main::before {
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(255, 255, 255, 0.6); /* 透明度50%の白いオーバーレイ */
        z-index: 1; /* オーバーレイがコンテンツの後ろに来ないように */
      }

      /* コンテンツをオーバーレイの上に表示するためのスタイル */
      main > * {
        position: relative;
        z-index: 2;
      }
    </style>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>

      <nav class="navbar navbar-expand-lg navbar-light py-5 bg-secondary bg-img">
  <div class="container-fluid">
    <%= link_to root_path do %>
          <%= image_tag 'naganoCAKE_logo2.jpg', size: '320x64', alt: "ながのケーキのアイコン", class: "header-icon" %>
        <% end %>




    <ul class="navbar-nav ms-auto">
      <% if customer_signed_in? %>
      <li class="nav-item">
       <div class="mt-2 mr-3 text-center">
        ようこそ、<%= current_customer.first_name %>さん！
       </div>
       </li>
      <% end %>

      <% if admin_signed_in? %>
        <li class="nav-item">
          <%= link_to "商品一覧", admin_items_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "会員一覧", admin_customers_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "注文履歴一覧", admin_root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% elsif customer_signed_in? %>
        <li class="nav-item">
          <%= link_to "マイページ", customers_my_page_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "商品一覧", items_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "カート", cart_items_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "About", homes_about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "商品一覧", items_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "新規登録", new_customer_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_customer_session_path, class: "nav-link" %>
        </li>

      <% end %>
    </ul>
    <div class="search-container">
      <input type="text" name="q" placeholder="検索">
    </div>
  </div>
</nav>







  <main class="mb-auto">
    <%= yield %>
  </main>


<footer>
  <div class='container-fluid bg-secondary'>
    <div class='row'>
      <div class='col text-center bg-img'>
        <p class="nav-item">©️CopyRight 天気のg子.inc</p>

      </div>
    </footer>
  </body>
</html>

app/views/publics/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>